CREATE TABLE USUARIO
(
  ID BIGINT NOT NULL PRIMARY KEY GENERATED ALWAYS AS IDENTITY (START WITH 1 INCREMENT BY 1),
  LOGIN VARCHAR(30) NOT NULL UNIQUE,
  NOME VARCHAR(30) NOT NULL,
  PASSWORD VARCHAR(30)  NOT NULL
);
